REM	#######################################################
REM	05_create_standard_roles.sql
REM	#######################################################


-----------------------------------------------------------------------------
CREATE ROLE VTA_DATA_SECURITY;
GRANT ALTER USER TO VTA_DATA_SECURITY;
GRANT CREATE USER TO VTA_DATA_SECURITY;
GRANT DROP USER TO VTA_DATA_SECURITY;
GRANT ANY ROLE TO VTA_DATA_SECURITY;
GRANT SELECT ANY DICTIONARY TO BCBSSC_DATA_SECURITY;

-----------------------------------------------------------------------------
CREATE ROLE VTA_DEVELOPER NOT IDENTIFIED;
GRANT CREATE PROCEDURE TO VTA_DEVELOPER;
GRANT CREATE SEQUENCE TO VTA_DEVELOPER;
GRANT CREATE SYNONYM TO VTA_DEVELOPER;
GRANT CREATE TABLE TO VTA_DEVELOPER;
GRANT CREATE TRIGGER TO VTA_DEVELOPER;
GRANT CREATE VIEW TO VTA_DEVELOPER;
GRANT DEBUG ANY PROCEDUIRE TO VTA_DEVELOPER;
GRANT DEBUG CONNECT SESSION TO VTA_DEVELOPER;
GRANT EXECUTE ON SYS.DBMS_SQL TO VTA_DEVELOPER;

-----------------------------------------------------------------------------
CREATE ROLE VTA_CONNECT;
GRANT CREATE_SESSION TO VTA_CONNECT;
-----------------------------------------------------------------------------
CREATE ROLE VTA_HELPDESK;
GRANT VTA_CONNECT TO VTA_HELPDESK;
GRANT ALTER USER TO VTA_HELPDESK;
GRANT SELECT ANY DICTIONARY TO VTA_HELPDESK;

-----------------------------------------------------------------------------

CREATE ROLE DB_ALL_VTA_ROLE;

GRANT SELECT ON V_$ASM_DISKGROUP TO DBA_ALL_VTA_ROLE;
GRANT SELECT ANY DICTIONARY TO DBA_ALL_VTA_ROLLE;

CREATE ROLLE OEM_MONITOR;

GRANT EXECUTE ON SYS.DBMS_SYSTEM TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_SERVER_ALERT TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_AQ TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_AQADM TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_DRS TO OEM_MONITOR;
GRANT EXECUTE ON SYS.ALERT_QUE TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_MONITOR TO OEM_MONITOR;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO OEM_MONITOR;

-----------------------------------------------------------------------------
GRANT SELECT ON DBSNMP.MGMT_BASELINE TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_BASELINE_SQL TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_LATEST TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_LATEST TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_HISTORY TO OEM_MONITOR;
GRANT SELECT ON DBSNMP.MGMT_HISTORY_SQL TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.MGMT_RESPONSE TO OEM_MONITOR;
GRANT EXECUTE ON DBSNMP.MGMT_UPDATE_DB_FEATURE_LOG TO OEM_MONITOR;


GRANT CREATE JOB TO OEM_MONITOR;
GRANT ADVISOR TO OEM_MONITOR;
GRANT ANALYZE ANY DICTIONARY TO OEM_MONITOR;
GRANT SELECT ANY DICTIONARY TO OEM_MONITOR;
GRANT ANALYZE ANY TO OEM_MONITOR;
GRANT CREATE SESSION TO OEM_MONITOR;

-----------------------------------------------------------------------------C





